#日志级别
logging:
  level:
   root: info

#数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smartcommunity?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456


#myBatis
mybatis:
  type-aliases-package: com.domain
  mapper-locations: classpath:com/mapper/*.xml
